Day-Walk/MLOps

- data/src/preprocessing/config.py
> ex) #5 
> 검색엔진 데이터 전처리 기능을 구현함.
>
> feat : 검색엔진 데이터 전처리 파일 추가

- MLOps/app/main.py
- MLOps/app/schema/recommendation_schema.py
- MLOps/app/services/deepctr_service.py
- MLOps/app/services/user_data_service.py
- start_all.sh
> ex) #11 
> 검색엔진 및 추천시스템 API 코드 수정 및 리팩토링
> refactor: 검색엔진 및 추천시스템 API 코드 수정 및 리팩토링

- ELK/Dockerfile
- ELK/docker-compose.yml
- ELK/requirements.txt
> ex) #14 
> AWS EC2 서버에서의 Docker 설정
> chore: EC2 ELK 서버 compose 정의

- data/src/place_api.py
> #4 
> 한국관광공사 공공데이터 api 호출해 장소 데이터 가져오기
> Refactor/장소 데이터 api 리팩토링

- data/src/place_enrich.py
> #19 
> 메타데이터 필터링 강화를 위한 장소데이터 지하철역, 행정구역 추가
> feat: 장소 데이터 메타데이터 보강

- ELK/docker-compose.yml
> ex) #21 
> ELK docker-compose 파일 수정
> `./esdata:/usr/share/elasticsearch/data` -> `/esdata:/usr/share/elasticsearch/data`
> chore: ELK docker-compose 파일 수정

- MLOps/docker-compose.yml
> ex) #26 
> docker compose elk api 연결 ip 변경
> Chore: docker compose ip 변경

- MLOps/requirements.txt
> Feat/챗봇 초기 모델 및 api

- .dvc/config
> chore: dvc config 수정

- ELK/app/main.py
- ELK/app/services/elasticsearch_service.py
> ex) #37 
> 연결 호스트 수정
> 헬스체크 엔드포인트 추가
> fix: Elasticsearch 연결 호스트 수정 및 헬스체크 엔드포인트 추가

- ELK/app/main.py
> fix: 절대 경로 설정

- ELK/docker-compose.yml
> fix: 오탈자 수정

- ELK/app/schema/search_schemas.py
- ELK/app/services/elasticsearch_service.py
> ex) #37 
> pydantic 오류 수정
> place_id -> uuid, sub_category -> subcategory
> fix: pydantic 문법 오류 수정 및 인덱스 이름 수정

- ELK/app/services/elasticsearch_service.py
> fix: pydantic 오류 수정

- MLOps/Dockerfile
> chore: pip 업그레이드 추가

- MLOps/requirements.txt
> ex) #57 
> requirements.txt 수정
> chore: requirements.txt에서 torch 관련 패키지 버전 수정

- MLOps/docker-compose.yml
> ex) #75 
> docker-compose 환경변수 추가
> chore: docker-compose.yml에 OPENAI_API_KEY 환경 변수 추가

- ELK/app/services/elasticsearch_service.py
> feat: 사용자별 로그 검색 기능 개선

- ELK/app/schema/log_schemas.py
- ELK/app/services/elasticsearch_service.py
> ex) #85 
> {location} : {"lat": float, "lng": float} 추가
> feat: 로그 스키마에 위치 정보 추가 및 Elasticsearch 매핑 수정

- MLOps/app/services/user_data_service.py
> ex) #90 
> 불러오는 데이터가 이상해서 특정 컬럼이 안 불러와지는 문제 해결
> fix: 사용자 데이터 경로 변경 및 사용자 정보 조회 기능 수정

- MLOps/app/services/db_connection.py
- MLOps/requirements.txt
- data/user_db.json.dvc
- data/user_like_db.json.dvc
> ex) #97 
> DB 접속 후 유저 정보 가져오기
> feat: db 접근 및 유저 데이터 사용

- ELK/app/main.py
> feat: LLM 도구를 위한 장소 검색 API의 카테고리 길이 제한 수정

- MLOps/app/services/chatbot_agent_service.py
> feat: 사용자 쿼리 기반 필터링 로직과 JSON 응답 처리 방식 업데이트

- MLOps/app/services/chatbot_agent_service.py
> feat: 챗봇 에이전트의 OpenAI 함수 에이전트에 대한 새로운 프롬프트 템플릿 추가 및 JSON 응답 처리 개선

- MLOps/app/routers/chatbot.py
> ex) #115 
> ChatbotAgentService 초기화 수정
> fix: ChatbotAgentService 초기화 시 OpenAI API 키 인자 제거

- MLOps/app/routers/chatbot.py
> fix: 챗봇 에이전트의 응답 처리 로직 수정 및 에러 핸들링 추가

- MLOps/app/services/chatbot_agent_service.py
> ex) #131 
> 유사도 검색 결과를 장소 목록으로 반환하도록 수정
> fix: ChatbotAgentService에서 검색 결과를 장소 목록으로 반환하도록 수정

- MLOps/app/services/chatbot_agent_service.py
> fix: ChatbotAgentService에서 검색 결과가 없을 경우 필터 없이 다시 검색하도록 로직 수정 및 반환 형식 개선

- MLOps/app/routers/chatbot.py
- MLOps/app/services/chatbot_agent_service.py
> fix: ChatbotAgentService의 응답 형식을 일관되게 수정

- MLOps/app/routers/chatbot.py
- MLOps/app/schema/chat_schema.py
- MLOps/app/services/chatbot_agent_service.py
> fix: 챗봇 응답 처리 로직을 개선

- ELK/app/schema/log_schemas.py
> ex) #159 
> chat log 저장 형식 수정
> fix: chat log 저장 형식 수정 - title 삭제

- .github/workflows/Deploy-ML-EC2.yml
- MLOps/app/main.py
- MLOps/app/model/deepfm_train.py
- MLOps/app/routers/crowd.py
- MLOps/app/schema/crowd_schema.py
- MLOps/app/services/deepctr_service.py
- MLOps/app/services/user_data_service.py
> ex) #163 
> 혼잡도 예측 API 및 스키마 추가
> 환경 변수 설정
> 배포 스크립트 수정
> Feat/혼잡도 api 생성

- MLOps/app/main.py
- MLOps/app/routers/crowd.py
> ex) #163 
> 혼잡도 API 재생성 및 수정
> feat: 혼잡도 예측 API 엔드포인트 및 상태 정보 추가

- data/congestion_preprocessing.py
> ex) #170 
> 혼잡도 데이터 전처리 코드 추가
> (선택사항)
> refactor: 혼잡도 예측 데이터 전처리 코드 추가

- ELK/app/main.py
- ELK/app/services/elasticsearch_service.py
> feat: 검색 로그 인덱스 생성 및 사용자 검색 로그 기록 기능 추가

- ELK/app/services/elasticsearch_service.py
- ELK/scripts/generate_dummy_data.py
> ex) #169 
> 더미 데이터 생성
> 사용자 클릭 데이터 반환 형식 변경
> Feat/es 검색 결과 저장

- MLOps/app/routers/crowd.py
- MLOps/app/services/langchain_agent_service.py
> ex) #190 
> 라우터 태그 변경
> 모델 버전 변경
> Fix/crowd api 수정

- .github/workflows/Deploy-ML-EC2.yml
> ex) #180 
> github action 파일 변경
> fix: Docker 배포 프로세스를 개선하여 컨테이너를 빌드하고 백그라운드에서 실행하도록 수정

- MLOps/docker-compose.yml
> ex) #180 
> docker compose 파일의 .env 파일 경로 변경
> fix: docker-compose.yml에서 환경 변수 파일 경로를 수정하여 .env 파일을 사용하도록 변경

- .github/workflows/Deploy-ML-EC2.yml
> ex) #180 
> github action 배포 설정 개선
> fix: Deploy-ML-EC2.yml에서 데이터베이스 관련 환경 변수를 추가하여 배포 설정 개선

- .github/workflows/Deploy-ML-EC2.yml
> fix: Deploy-ML-EC2.yml에 데이터베이스 관련 환경 변수를 추가하여 배포 설정을 더욱 개선함

- MLOps/docker-compose.yml
> feat: Docker Compose 파일에 서울 시간대 환경 변수 추가

- MLOps/app/python_schedule/data/crowd_prediction.dvc
- MLOps/app/services/predict_cong_service.py
- MLOps/docker-compose.yml
> ex) #222 
> 쌓인 데이터 dvc 추가
> 경로 수정
> Feat/혼잡도 api 내부 로직 구현

- ELK/app/services/elasticsearch_service.py
- data/src/utils/es_place_upload.py
> ex) #240 
> 데이터 색인 과정 copy_to 추가 - categories, addresses
> 장소 검색 기능 고도화 - 가중치 부여
> llm search tool 랜덤성 추가
> Feat/es 검색엔진 고도화

- ELK/app/services/elasticsearch_service.py
> ex) #240 
> 검색 엔진 인덱스 가중치 조정
> feat: Elasticsearch 검색 쿼리의 가중치 조정

- ELK/app/main.py
- ELK/app/services/elasticsearch_service.py
> ex) #245 
> 로그 데이터의 타임 스탬프를 KST로 변경
> fix: 로그 데이터의 타임스탬프를 서울 시간대로 변경

- MLOps/Dockerfile
> ex) #263 
> Dockerfile에 필요 패키지 설치 추가
> fix: Dockerfile에 libgomp1 패키지 설치 추가

- MLOps/Dockerfile
> ex) #263 
> Dockerfile libgomp1 패키지 설치 방법 수정
> fix: Dockerfile에서 libgomp1 패키지 설치 방법 수정

- MLOps/app/routers/crowd.py
- MLOps/app/services/langchain_agent_service.py
- data/chroma_db_bge.dvc
> ex) #278 
> API에 지역 필터링 기능 추가
> chroma db 갱신 (meta에 area 데이터 추가)
> Feat/챗봇 혼잡도 안내 추가

- ELK/app/services/elasticsearch_service.py
> ex) #280 
> 검색 기능 개선 -> 카테고리 필터링 로직 추가
> feat: 장소 검색 기능 개선 및 카테고리 필터링 로직 추가

- MLOps/app/routers/crowd.py
- MLOps/app/services/langchain_agent_service.py
> ex) #290 
> 챗봇 온도 조절
> 혼잡도 예측 도구 수정 및 프롬프트 수정
> 혼잡도 API 에서 다수 지역 조회 가능하도록 수정
> Feat/챗봇 혼잡도 툴 추가

- ELK/app/services/elasticsearch_service.py
> ex) #294 
> 최근 24시간 클릭 수 많은 장소 4개 반환으로 수정
> feat: 클릭 수 집계 로직 개선 및 시간 범위 수정

- ELK/app/services/elasticsearch_service.py
- MLOps/app/services/deepctr_service.py
- MLOps/app/services/elk_client.py
> fix: 장소 검색 기능에 사용자 ID 파라미터 추가 및 로그 기록 방식 개선
